version: "3.7"

services:
  backend:
    build: "./backend"
    container_name: backend
    depends_on:
      - adonis_db
    ports:
      - "3333:3333"
    command: >
      sh -c "node ace migration:run && npm start"
    networks:
      - dojo-network

  frontend:
    build: "./frontend"
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"

  adonis_db:
    image: mysql
    container_name: adonis_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "adonis"
      MYSQL_DATABASE: "adonis"
    networks:
      - dojo-network
    command: --default-authentication-plugin=mysql_native_password

networks:
  dojo-network:
